spring:
  application:
    name: invoice
  datasource:
    url: jdbc:h2:mem:invoice
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console